import { useCallback, useEffect, useState } from "react";
import { api } from "../../services/api";
import { messageFrom } from "../../lib/errors";
import { AnalysisLanguageToggle, type AnalysisLocale } from "../localization/AnalysisLanguageToggle";
import type { CompetitorAnalysis, CompetitorAnalysisStatus, CompetitorVideo, LocalizedCompetitorAnalysisContent } from "../competitors/types";

export function AnalysisPanel({ projectId, competitor }: { projectId: string; competitor: { id: string; videos: CompetitorVideo[] } }) {
  const [status, setStatus] = useState<CompetitorAnalysisStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [locale, setLocale] = useState<AnalysisLocale>("en");
  const [localized, setLocalized] = useState<LocalizedCompetitorAnalysisContent | null>(null);
  const [localizedAnalysisId, setLocalizedAnalysisId] = useState<string | null>(null);
  const [localizing, setLocalizing] = useState(false);
  const [localizationError, setLocalizationError] = useState<string | null>(null);
  const active = status?.activeJob?.status === "Queued" || status?.activeJob?.status === "Running" || status?.activeJob?.status === "Retrying";
  const load = useCallback(async () => { try { setStatus(await api.getCompetitorAnalysis(projectId, competitor.id)); setError(null); } catch (requestError) { setError(messageFrom(requestError)); } finally { setLoading(false); } }, [projectId, competitor.id]);
  useEffect(() => { void Promise.resolve().then(load); return undefined; }, [load]);
  useEffect(() => { if (!active) return undefined; const timer = window.setInterval(() => void load(), 2000); return () => window.clearInterval(timer); }, [active, load]);
  const loadLocalization = useCallback(async (analysisId: string) => {
    const translation = await api.getCompetitorAnalysisLocalization(projectId, competitor.id, analysisId, "vi");
    if (translation.content) { setLocalized(translation.content); setLocalizedAnalysisId(analysisId); setLocalizing(false); setLocalizationError(null); return; }
    setLocalizing(Boolean(translation.activeJob));
    if (translation.latestJob?.status === "Failed") setLocalizationError(translation.latestJob.failureReason ?? "Vietnamese analysis translation failed. English remains available.");
  }, [competitor.id, projectId]);
  useEffect(() => { const analysisId = status?.latestAnalysis?.id; if (locale !== "vi" || !analysisId || !localizing) return undefined; const timer = window.setInterval(() => void loadLocalization(analysisId), 2000); return () => window.clearInterval(timer); }, [loadLocalization, locale, localizing, status?.latestAnalysis?.id]);
  async function changeLocale(nextLocale: AnalysisLocale) { setLocale(nextLocale); if (nextLocale === "en") return; const analysisId = status?.latestAnalysis?.id; if (!analysisId || (localizedAnalysisId === analysisId && localized)) return; setLocalizing(true); setLocalizationError(null); try { await api.requestCompetitorAnalysisLocalization(projectId, competitor.id, analysisId, "vi"); await loadLocalization(analysisId); } catch (requestError) { setLocalizing(false); setLocalizationError(messageFrom(requestError)); } }
  async function run() { setRunning(true); setError(null); try { await api.runCompetitorAnalysis(projectId, competitor.id); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setRunning(false); } }
  const currentAnalysis = status?.latestAnalysis;
  return <section className="analysis-section panel"><div className="section-heading"><div><span className="eyebrow">AI Analysis</span><h2>Competitor intelligence</h2></div>{currentAnalysis && <div className="idea-actions"><AnalysisLanguageToggle locale={locale} onChange={(next) => void changeLocale(next)} /><span>Version {currentAnalysis.version}</span></div>}</div>
    {loading ? <p className="empty-state">Loading analysis…</p> : error ? <><p className="error-copy" role="alert">{error}</p><button className="primary-button" type="button" onClick={() => void load()}>Retry</button></> : active ? <div className="analysis-state"><strong>Analyzing competitor…</strong><span>Status: {status?.activeJob?.status}</span></div> : status?.latestJob?.status === "Failed" ? <div className="analysis-state"><p role="alert">{status.latestJob.failureReason ?? "Analysis failed. You can retry safely."}</p><button className="primary-button" type="button" onClick={() => void run()} disabled={running}>Run AI Analysis</button></div> : currentAnalysis ? <><AnalysisReport analysis={currentAnalysis} videos={competitor.videos} localized={locale === "vi" && localizedAnalysisId === currentAnalysis.id ? localized : null} />{locale === "vi" && localizing && <p className="empty-state">Preparing Vietnamese analysis reading aid…</p>}{locale === "vi" && localizationError && <p className="error-copy" role="alert">{localizationError}</p>}</> : <div className="analysis-state"><p>No analysis has been generated yet.</p><button className="primary-button" type="button" onClick={() => void run()} disabled={running}>{running ? "Queuing analysis…" : "Run AI Analysis"}</button></div>}
  </section>;
}

function AnalysisBlock({ title, children }: { title: string; children: React.ReactNode }) { return <section className="analysis-block"><h3>{title}</h3>{children}</section>; }
function Evidence({ names }: { names: string[] }) { return names.length ? <small className="evidence">Observed in: {names.join(" · ")}</small> : null; }
function AnalysisReport({ analysis, videos, localized }: { analysis: CompetitorAnalysis; videos: CompetitorVideo[]; localized: LocalizedCompetitorAnalysisContent | null }) {
  const result = analysis.result; const videoTitles = new Map(videos.map((video) => [video.id, video.title])); const names = (ids: string[]) => ids.map((id) => videoTitles.get(id)).filter((title): title is string => Boolean(title));
  return <div className="analysis-report">{analysis.isStale && <p className="stale-note">This analysis may be outdated because the competitor data was refreshed after it ran.</p>}<div className="confidence-grid"><div><span>Overall confidence</span><strong>{result.confidence.overallConfidence}%</strong></div><div><span>Data quality</span><strong>{localized?.confidence?.dataQuality ?? result.confidence.dataQuality}</strong></div><div><span>Evidence window</span><strong>{analysis.analyzedVideoCount} videos</strong></div></div>
    <AnalysisBlock title="Target audience"><p>{result.audience.likelyAgeRange && `Likely age: ${localized?.audience?.likelyAgeRange ?? result.audience.likelyAgeRange}`}</p><p>{(localized?.audience?.likelyInterests ?? result.audience.likelyInterests).join(" · ")}</p><p>{(localized?.audience?.likelyViewerIntent ?? result.audience.likelyViewerIntent).join(" · ")}</p></AnalysisBlock>
    <AnalysisBlock title="Topic clusters">{result.topicClusters.map((item, index) => <article key={item.name}><strong>{localized?.topicClusters?.[index]?.name ?? item.name}</strong><p>{localized?.topicClusters?.[index]?.description ?? item.description}</p><small>{item.frequency} observed · {localized?.topicClusters?.[index]?.performanceSignal ?? item.performanceSignal} · {item.confidence}% confidence</small><Evidence names={names(item.exampleVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Winning title patterns">{result.titlePatterns.map((item, index) => <article key={item.patternName}><strong>{localized?.titlePatterns?.[index]?.patternName ?? item.patternName}</strong><p>{localized?.titlePatterns?.[index]?.description ?? item.description}</p><code>{item.template}</code><p>{item.exampleTitles.join(" · ")}</p><small>{item.observedFrequency} observed · {localized?.titlePatterns?.[index]?.performanceSignal ?? item.performanceSignal}</small></article>)}</AnalysisBlock>
    <AnalysisBlock title="Thumbnail patterns">{result.thumbnailPatterns.map((item, index) => <article key={item.patternName}><strong>{localized?.thumbnailPatterns?.[index]?.patternName ?? item.patternName}</strong><p>{localized?.thumbnailPatterns?.[index]?.observation ?? item.observation}</p><small>{item.confidence}% confidence · {(localized?.thumbnailPatterns?.[index]?.limitations ?? item.limitations).join(" ")}</small><Evidence names={names(item.evidenceVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Hook patterns">{result.hookPatterns.map((item, index) => <article key={item.patternName}><strong>{localized?.hookPatterns?.[index]?.patternName ?? item.patternName}</strong><p>{localized?.hookPatterns?.[index]?.observation ?? item.observation}</p><small>{item.confidence}% confidence · {(localized?.hookPatterns?.[index]?.limitations ?? item.limitations).join(" ")}</small><Evidence names={names(item.evidenceVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Content formats">{result.contentFormats.map((item, index) => <article key={item.format}><strong>{localized?.contentFormats?.[index]?.format ?? item.format}</strong><p>{localized?.contentFormats?.[index]?.performanceSignal ?? item.performanceSignal} · {item.confidence}% confidence</p><Evidence names={names(item.evidenceVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Performance patterns">{result.performanceInsights.map((item, index) => <article key={index}><p>{localized?.performanceInsights?.[index]?.insight ?? item.insight}</p><Evidence names={names(item.supportingVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Potential weaknesses">{result.potentialWeaknesses.map((item, index) => <article key={index}><p>{localized?.potentialWeaknesses?.[index]?.observation ?? item.observation}</p><Evidence names={names(item.supportingVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Transferable formats">{result.transferableFormats.map((item, index) => <article key={item.format}><strong>{localized?.transferableFormats?.[index]?.format ?? item.format}</strong><p>{localized?.transferableFormats?.[index]?.whyItMayWork ?? item.whyItMayWork}</p><p>{localized?.transferableFormats?.[index]?.transferableMechanic ?? item.transferableMechanic}</p><small>Do not copy: {localized?.transferableFormats?.[index]?.doNotCopy ?? item.doNotCopy}</small><Evidence names={names(item.evidenceVideoIds)} /></article>)}</AnalysisBlock>
    <AnalysisBlock title="Evidence & limitations"><ul>{(localized?.confidence?.limitations ?? result.confidence.limitations).map((item) => <li key={item}>{item}</li>)}{result.evidenceNotes.map((item, index) => <li key={item.note}>{localized?.evidenceNotes?.[index]?.note ?? item.note}</li>)}</ul></AnalysisBlock>
  </div>;
}
