// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoutubeAiFactory.Infrastructure.Persistence;

#nullable disable

namespace YoutubeAiFactory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YoutubeAiFactoryDbContext))]
    [Migration("20260911163755_EnforcePilotExperimentBlocks")]
    partial class EnforcePilotExperimentBlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("yaf")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YoutubeAiFactory.Domain.AI.AiRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompetitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("LatencyMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_milliseconds");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_key");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Workflow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflow");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId", "StartedAt");

                    b.HasIndex("ProjectId", "StartedAt");

                    b.ToTable("ai_runs", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_run_id");

                    b.Property<int>("AnalyzedVideoCount")
                        .HasColumnType("integer")
                        .HasColumnName("analyzed_video_count");

                    b.Property<Guid>("CompetitorChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_key");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset>("SourceDataAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_data_as_of");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorChannelId", "CreatedAt");

                    b.HasIndex("CompetitorChannelId", "Version")
                        .IsUnique();

                    b.ToTable("competitor_analyses", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Handle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handle");

                    b.Property<DateTimeOffset>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_collected_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<long?>("SubscriberCount")
                        .HasColumnType("bigint")
                        .HasColumnName("subscriber_count");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<long?>("VideoCount")
                        .HasColumnType("bigint")
                        .HasColumnName("video_count");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("youtube_channel_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("competitor_channels", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<long?>("CommentCount")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_count");

                    b.Property<Guid>("CompetitorChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("youtube_video_id");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorChannelId", "YoutubeVideoId")
                        .IsUnique();

                    b.ToTable("competitor_videos", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.IdeaEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idea_id");

                    b.Property<Guid>("OpportunityEvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_evidence_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityEvidenceId");

                    b.HasIndex("IdeaId", "OpportunityEvidenceId")
                        .IsUnique();

                    b.ToTable("idea_evidence", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.IdeaGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<Guid>("OpportunityReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_report_id");

                    b.Property<int>("OpportunityReportVersion")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_report_version");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_key");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ScoringAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scoring_algorithm_version");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityReportId");

                    b.HasIndex("OpportunityId", "Version")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("idea_generations", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.VideoIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Angle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("AudienceFit")
                        .HasColumnType("integer")
                        .HasColumnName("audience_fit");

                    b.Property<int>("CompetitionRisk")
                        .HasColumnType("integer")
                        .HasColumnName("competition_risk");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content_format");

                    b.Property<string>("CoreQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("core_question");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision_status");

                    b.Property<decimal>("DuplicationPenalty")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("duplication_penalty");

                    b.Property<int>("EvidenceStrength")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_strength");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<string>("HookConcept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hook_concept");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Novelty")
                        .HasColumnType("integer")
                        .HasColumnName("novelty");

                    b.Property<int>("ObservedDemandAlignment")
                        .HasColumnType("integer")
                        .HasColumnName("observed_demand_alignment");

                    b.Property<int>("OpportunityFit")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_fit");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<int>("ProductionEase")
                        .HasColumnType("integer")
                        .HasColumnName("production_ease");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ResearchRisk")
                        .HasColumnType("integer")
                        .HasColumnName("research_risk");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risks_json");

                    b.Property<string>("ScoringAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scoring_algorithm_version");

                    b.Property<int>("StoryPotential")
                        .HasColumnType("integer")
                        .HasColumnName("story_potential");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("target_audience");

                    b.Property<string>("ThumbnailConcept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_concept");

                    b.Property<int>("ThumbnailPotential")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_potential");

                    b.Property<int>("TitlePotential")
                        .HasColumnType("integer")
                        .HasColumnName("title_potential");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ViewerIntent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("viewer_intent");

                    b.Property<string>("ViewerPromise")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("viewer_promise");

                    b.Property<string>("WhyViewerWouldCare")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("why_viewer_would_care");

                    b.Property<string>("WorkingTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("working_title");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("OpportunityId", "OverallScore");

                    b.HasIndex("ProjectId", "DecisionStatus");

                    b.ToTable("video_ideas", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid?>("CompetitorChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorChannelId")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_active_competitor_analysis")
                        .HasFilter("type = 'competitor-analysis' AND status IN ('Queued', 'Running', 'Retrying')");

                    b.HasIndex("OpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_active_idea_generation")
                        .HasFilter("type = 'idea-generation' AND status IN ('Queued', 'Running', 'Retrying')");

                    b.HasIndex("ProjectId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_active_project_analysis")
                        .HasFilter("type IN ('opportunity-analysis', 'pilot-generation') AND status IN ('Queued', 'Running', 'Retrying')");

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("jobs", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Angle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("AudienceFitSignal")
                        .HasColumnType("integer")
                        .HasColumnName("audience_fit_signal");

                    b.Property<int>("CompetitionRiskSignal")
                        .HasColumnType("integer")
                        .HasColumnName("competition_risk_signal");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EvidenceStrength")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_strength");

                    b.Property<string>("LimitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NoveltySignal")
                        .HasColumnType("integer")
                        .HasColumnName("novelty_signal");

                    b.Property<int>("ObservedDemandSignal")
                        .HasColumnType("integer")
                        .HasColumnName("observed_demand_signal");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<int>("ProductionComplexity")
                        .HasColumnType("integer")
                        .HasColumnName("production_complexity");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risks_json");

                    b.Property<int>("StoryPotential")
                        .HasColumnType("integer")
                        .HasColumnName("story_potential");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TransferabilitySignal")
                        .HasColumnType("integer")
                        .HasColumnName("transferability_signal");

                    b.Property<string>("WhyThisOpportunity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("why_this_opportunity");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "OverallScore");

                    b.ToTable("opportunity_candidates", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<Guid>("CompetitorAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_analysis_id");

                    b.Property<Guid>("CompetitorChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<Guid?>("CompetitorVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_video_id");

                    b.Property<string>("EvidenceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorAnalysisId");

                    b.HasIndex("CompetitorChannelId");

                    b.HasIndex("CompetitorVideoId");

                    b.HasIndex("CandidateId", "EvidenceId")
                        .IsUnique();

                    b.ToTable("opportunity_evidence", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LimitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations_json");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_key");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ScoringAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scoring_algorithm_version");

                    b.Property<int>("SourceAnalysisCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_analysis_count");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique();

                    b.ToTable("opportunity_reports", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityReportSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitorAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_analysis_id");

                    b.Property<int>("CompetitorAnalysisVersion")
                        .HasColumnType("integer")
                        .HasColumnName("competitor_analysis_version");

                    b.Property<Guid>("CompetitorChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_channel_id");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorAnalysisId");

                    b.HasIndex("CompetitorChannelId");

                    b.HasIndex("ReportId", "CompetitorAnalysisId")
                        .IsUnique();

                    b.ToTable("opportunity_report_sources", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Pilots.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_run_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("AssumptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assumptions_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EligibleIdeaCount")
                        .HasColumnType("integer")
                        .HasColumnName("eligible_idea_count");

                    b.Property<string>("LimitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations_json");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("PlanningAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("planning_algorithm_version");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_key");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique();

                    b.ToTable("pilots", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Pilots.PilotVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ControlStrategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_strategy");

                    b.Property<string>("ExperimentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("experiment_type");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hypothesis");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("uuid")
                        .HasColumnName("pilot_id");

                    b.Property<string>("PrimaryMetric")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("primary_metric");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("SecondaryMetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("secondary_metrics_json");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("SuccessSignal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("success_signal");

                    b.Property<string>("VariableBeingTested")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variable_being_tested");

                    b.Property<Guid>("VideoIdeaId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_idea_id");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VideoIdeaId");

                    b.HasIndex("PilotId", "Sequence")
                        .IsUnique();

                    b.HasIndex("PilotId", "VideoIdeaId")
                        .IsUnique();

                    b.ToTable("pilot_videos", "yaf", t =>
                        {
                            t.HasCheckConstraint("ck_pilot_videos_experiment_block", "(sequence BETWEEN 1 AND 4 AND experiment_type = 'Topic') OR (sequence BETWEEN 5 AND 8 AND experiment_type = 'Packaging') OR (sequence BETWEEN 9 AND 12 AND experiment_type = 'Storytelling')");

                            t.HasCheckConstraint("ck_pilot_videos_sequence", "sequence >= 1 AND sequence <= 12");
                        });
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("projects", "yaf");
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.AI.AiRun", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorAnalysis", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", null)
                        .WithMany()
                        .HasForeignKey("CompetitorChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorVideo", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", null)
                        .WithMany("Videos")
                        .HasForeignKey("CompetitorChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.IdeaEvidence", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Ideas.VideoIdea", null)
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityEvidence", null)
                        .WithMany()
                        .HasForeignKey("OpportunityEvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.IdeaGeneration", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityReport", null)
                        .WithMany()
                        .HasForeignKey("OpportunityReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Ideas.VideoIdea", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Ideas.IdeaGeneration", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityEvidence", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorAnalysis", null)
                        .WithMany()
                        .HasForeignKey("CompetitorAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", null)
                        .WithMany()
                        .HasForeignKey("CompetitorChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorVideo", null)
                        .WithMany()
                        .HasForeignKey("CompetitorVideoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityReport", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Opportunities.OpportunityReportSource", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorAnalysis", null)
                        .WithMany()
                        .HasForeignKey("CompetitorAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", null)
                        .WithMany()
                        .HasForeignKey("CompetitorChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Pilots.Pilot", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Pilots.PilotVideo", b =>
                {
                    b.HasOne("YoutubeAiFactory.Domain.Opportunities.OpportunityCandidate", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Pilots.Pilot", null)
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoutubeAiFactory.Domain.Ideas.VideoIdea", null)
                        .WithMany()
                        .HasForeignKey("VideoIdeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Projects.Project", b =>
                {
                    b.OwnsOne("YoutubeAiFactory.Domain.Projects.AudienceProfile", "Audience", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("audience_description");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects", "yaf");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("YoutubeAiFactory.Domain.Projects.Market", "Market", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("market_name");

                            b1.Property<string>("TargetGeography")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("target_geography");

                            b1.Property<string>("TargetLanguage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("target_language");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects", "yaf");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Audience")
                        .IsRequired();

                    b.Navigation("Market")
                        .IsRequired();
                });

            modelBuilder.Entity("YoutubeAiFactory.Domain.Competitors.CompetitorChannel", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
