using YoutubeAiFactory.Application.Competitors;
using YoutubeAiFactory.Application.Ideas;
using YoutubeAiFactory.Application.Localization;
using YoutubeAiFactory.Application.Opportunities;
using YoutubeAiFactory.Application.Outlines;
using YoutubeAiFactory.Application.Pilots;
using YoutubeAiFactory.Application.Research;
using YoutubeAiFactory.Application.Scripts;
using YoutubeAiFactory.Infrastructure;
using YoutubeAiFactory.Worker;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddInfrastructure(builder.Configuration);
builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddSingleton(builder.Configuration.GetSection("CompetitorAnalysis").Get<CompetitorAnalysisOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection("OpportunityAnalysis").Get<OpportunityAnalysisOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection("IdeaGeneration").Get<IdeaGenerationOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection("PilotGeneration").Get<PilotGenerationOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection(ArtifactLocalizationOptions.SectionName).Get<ArtifactLocalizationOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection(ResearchOptions.SectionName).Get<ResearchOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection(OutlineOptions.SectionName).Get<OutlineOptions>() ?? new());
builder.Services.AddSingleton(builder.Configuration.GetSection(ScriptOptions.SectionName).Get<ScriptOptions>() ?? new());
builder.Services.AddScoped<CompetitorAnalysisContextBuilder>();
builder.Services.AddScoped<CompetitorAnalysisJobProcessor>();
builder.Services.AddScoped<OpportunityAnalysisContextBuilder>();
builder.Services.AddScoped<OpportunityScoringEngine>();
builder.Services.AddScoped<OpportunityAnalysisJobProcessor>();
builder.Services.AddScoped<IdeaGenerationContextBuilder>();
builder.Services.AddScoped<IdeaScoringEngine>();
builder.Services.AddScoped<IdeaGenerationJobProcessor>();
builder.Services.AddScoped<PilotGenerationContextBuilder>();
builder.Services.AddScoped<PilotGenerationJobProcessor>();
builder.Services.AddScoped<RequestCompetitorAnalysisLocalizationHandler>();
builder.Services.AddScoped<GetCompetitorAnalysisLocalizationHandler>();
builder.Services.AddScoped<ArtifactLocalizationJobProcessor>();
builder.Services.AddScoped<VideoResearchJobProcessor>();
builder.Services.AddScoped<OutlineGenerationContextBuilder>();
builder.Services.AddScoped<OutlineValidator>();
builder.Services.AddScoped<VideoOutlineJobProcessor>();
builder.Services.AddScoped<ScriptGenerationContextBuilder>();
builder.Services.AddScoped<ScriptValidator>();
builder.Services.AddScoped<VideoScriptJobProcessor>();
builder.Services.AddHostedService<DatabaseHeartbeatWorker>();
builder.Services.AddHostedService<CompetitorAnalysisWorker>();
builder.Services.AddHostedService<OpportunityAnalysisWorker>();
builder.Services.AddHostedService<IdeaGenerationWorker>();
builder.Services.AddHostedService<PilotGenerationWorker>();
builder.Services.AddHostedService<ArtifactLocalizationWorker>();
builder.Services.AddHostedService<VideoResearchWorker>();
builder.Services.AddHostedService<VideoOutlineWorker>();
builder.Services.AddHostedService<VideoScriptWorker>();

var host = builder.Build();
host.Run();
